### ISSUE TITLE
Checkout fails on Windows due to invalid file names

### ISSUE THREAD

**Issue by zoomorph** [discogs/discogs_client#37]
Git checkout of repository fails....
error: unable to create file discogs_client/tests/res/artists/1/releases?per_page=50&page=1.json (Invalid argument)
error: unable to create file discogs_client/tests/res/artists/1/releases?per_page=50&page=2.json (Invalid argument)
error: unable to create file discogs_client/tests/res/database/search?q=trash80&per_page=50&page=1.json (Invalid argument)
error: unable to create file discogs_client/tests/res/masters/4242/versions?per_page=50&page=1.json (Invalid argument)
error: unable to create file discogs_client/tests/res/users/example/wants?per_page=50&page=1.json (Invalid argument)

**Comment by JonathonSonesen** [comment]
Also, the path names are invalid for windows which uses the back slash character unlike unix systems which use the forward slash

**Comment by JonathonSonesen** [comment]
Here is the list of invalid file name characters:
\ / ? : * " > < |

**Comment by leo-dor** [comment]
Another workaround is to make FilesystemFetcher replace '?' with '_' in the URL, and change existing filenames accordingly.

**Comment by JonathonSonesen** [comment]
I was thinking about this recently and realized after seeing that those files are sym links that the checkout would have to be done using cygwin. I have not tried this yet because I am taking a discrete math class, a calculus class, and a machine architecture class right now so time is precious. After June 10th though I would like to start looking into making a portable branch.... not sure if it will get done but I shall try.

**Comment by leo-dor** [comment]
I've added logic to resolve parameter lists to existing files, see pull request above. It clones OK now.
Best of luck with your studies!

**Comment by leo-dor** [comment]
This is now fixed, can you close the issue?
